language: objective-c
xcode_project: JKRBubblePresent.xcodeproj
xcode_scheme: JKRBubblePresent
osx_image: xcode8.0
script: xcodebuild -project JKRBubblePresent.xcodeproj -scheme "JKRBubblePresent" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
